name: 🚀 Deploy to Hostinger via FTP

on:
  push:
    branches:
      - main

jobs:
  ftp-deploy:
    name: Upload Website via FTP
    runs-on: ubuntu-latest

    steps:
    - name: 📥 Checkout Repository
      uses: actions/checkout@v3

    - name: 📤 Upload files via FTP
      uses: SamKirkland/FTP-Deploy-Action@v4.3.4
      with:
        server: ${{ secrets.FTP_HOST }}
        username: ${{ secrets.FTP_USERNAME }}
        password: ${{ secrets.FTP_PASSWORD }}
        port: ${{ secrets.FTP_PORT }}
        protocol: ftp
        local-dir: ./             # Current directory with your built files
        server-dir: ./           # Since FTP connects directly to public_html
        gitignore: true          # Automatically ignore git-tracked ignored files
        dangerous-clean-slate: false  # Set true to delete remote files not in local
        exclude: |
          **/.git/**
          **/.github/**
          **/.gitignore
          **/.gitattributes
          **/.gitmodules
          **/README.md
          **/LICENSE
         
        log-level: verbose
      env:
        FTP_SECURE: false         # Often needed for Hostinger
